BEGIN;

CREATE TABLE IF NOT EXISTS mos (
    id_mo VARCHAR(255) PRIMARY KEY NOT NULL,
    id_product VARCHAR(255) NOT NULL,
    id_bom VARCHAR(255) NOT NULL,
    qtytoproduce VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

COMMIT;
