version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - redis
      - db
    environment:
      ENV: "dev"
      PORT: "8088"
      POSTGRES_HOST: "db"          # ganti localhost dengan db
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "parfume-erp"
      POSTGRES_PASSWORD: "parfume-erp"
      POSTGRES_DATABASE: "parfume-erp"
      REDIS_HOST: "redis"          # ganti localhost dengan redis
      REDIS_PORT: "6379"
      JWT_SECRET_KEY: "erwhdhsajdahjkdhqwiuou"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=parfume-erp
      - POSTGRES_PASSWORD=parfume-erp
      - POSTGRES_DB=parfume-erp
    ports:
      - "5432:5432"
